sudo: required
services:
  - docker

env:
    global:
      - SHA=$(git rev-parse HEAD)
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_4e730d7d99c5_key -iv $encrypted_4e730d7d99c5_iv -in multi-k8s-241916-ff45836a8861.json.enc -out multi-k8s-241916-ff45836a8861.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-241916-ff45836a8861.json
  - gcloud config set project multi-k8s-241916
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t heroahmadi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run heroahmadi/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master