sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_4e730d7d99c5_key -iv $encrypted_4e730d7d99c5_iv -in multi-k8s-241916-ff45836a8861.json.enc -out multi-k8s-241916-ff45836a8861.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json